name: Go

on:
  push:
    branches: [ master, main, v1, v2 ]
  pull_request:
    branches: [ master, main, v1, v2 ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - name: Set up GOPRIVATE
        run: go env -w GOPRIVATE=github.com

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
